project:
  name: aviation_weather_disruption
  review: progress_review_1

dataset:
  source_name: ARCO_ERA5
  zarr_url: "gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3"

  # Keep Progress Review 1 small.
  start_time: "2022-01-01T00:00:00"
  end_time: "2022-01-03T23:00:00"

  variables:
    - "2m_temperature"
    - "10m_u_component_of_wind"
    - "10m_v_component_of_wind"
    - "total_precipitation"
    - "surface_pressure"
    - "convective_available_potential_energy"

airports:
  JFK:
    name: "John F. Kennedy International Airport"
    lat: 40.6413
    lon: -73.7781

kafka:
  bootstrap_servers: "kafka:9092"
  topic_weather_raw: "weather.raw"

minio:
  endpoint: "http://minio:9000"
  raw_bucket: "raw"
  lakehouse_bucket: "lakehouse"